[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://github.com/iced-rs/iced.git?branch=master"]
git = "https://github.com/iced-rs/iced.git"
branch = "master"
replace-with = "vendored-sources"

[source."git+https://github.com/iced-rs/winit.git?rev=11414b6aa45699f038114e61b4ddf5102b2d3b4b"]
git = "https://github.com/iced-rs/winit.git"
rev = "11414b6aa45699f038114e61b4ddf5102b2d3b4b"
replace-with = "vendored-sources"

[source."git+https://github.com/iced-rs/cryoglyph.git?rev=a456d1c17bbcf33afcca41d9e5e299f9f1193819"]
git = "https://github.com/iced-rs/cryoglyph.git"
rev = "a456d1c17bbcf33afcca41d9e5e299f9f1193819"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor" 